version: 2.1
jobs:
  build:
    machine:
        image: ubuntu-2004:202008-01
    steps:
      - checkout
      - restore_cache:
          key: groups-dependency-cache-{{ checksum "pom.xml" }}
      - run:
          name: Build the code
          command: mvn clean install
      - run:
          name: Save the build artifact
          command: cd service && mvn play2:dist
      - save_cache:
          key: groups-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - store_artifacts:
          path: service/target/group-service-1.0.0-dist.zip
          destination: "/tmp/group-service.zip"
      - run:
          name: sonar
          command: mvn verify -DskipTests sonar:sonar -Dsonar.projectKey=sunbird-lern_groups-service -Dsonar.organization=sunbird-lern -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.exclusions=**/cassandra-utils/**,**/platform-cache/**,**/sb-actor/**,**/sb-telemetry-utils/**,**/sb-utils/**,**/models/**,**/bean/*,**/sb-common/** -Dsonar.coverage.jacoco.xmlReportPaths=/home/circleci/project/reports/target/jacoco/jacoco.xml
workflows:
  version: 2.1
  workflow:
    jobs:
      - build
