name: Pull Request Analysis

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  Run-test-cases:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: groups-dependency-cache-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            groups-dependency-cache-

      - name: Build and Run test cases
        run: mvn clean install

      - name: Save the build artifact
        run: cd service && mvn play2:dist

      - name: Save Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: groups-dependency-cache-${{ hashFiles('**/pom.xml') }}

      - name: Store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: group-service
          path: service/target/group-service-1.0.0-dist.zip

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
     
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B verify -DskipTests org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=Sunbird-Lern_groups-service \
            -Dsonar.organization=sunbird-lern \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.exclusions=**/cassandra-utils/**,**/platform-cache/**,**/sb-actor/**,**/sb-telemetry-utils/**,**/sb-utils/**,**/models/**,**/bean/*,**/sb-common/** \
            -Dsonar.coverage.jacoco.xmlReportPaths=/home/runner/work/groups-service/groups-service/reports/target/jacoco/jacoco.xml